name: firebase_core_desktop_new

description: Desktop implementation of firebase_core
homepage: https://firebase.flutter.dev

repository: https://github.com/Danroyal001/firebase_core_desktop_new

version: 1.0.0

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=1.20.0'

dependencies:
  firebase_core_dart_new: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  firebase_core: ^3.6.0
  firebase_core_platform_interface: ^5.3.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  plugin_platform_interface: ^2.1.8

flutter:
  plugin:
    implements: firebase_core
    platforms:
      # TODO when doing development on macOS, uncomment this.
      # macos:
      #   dartPluginClass: FirebaseCore
      #   pluginClass: none
      linux:
        dartPluginClass: FirebaseCore
        pluginClass: none
      windows:
        dartPluginClass: FirebaseCore
        pluginClass: none

false_secrets:
  - /example/lib/main.dart
